.TH GOLEM 1 "JAN 2010" Linux "User Manuals"
.SH NAME
golem \- Pythons game framework

.SH SYNOPSIS
.B golem
[filename]

.SH DESCRIPTION
Golem is Pythons game framework for 2D games - strategies, arcades etc.

.TP
.B More information
 Project Website: http://
 Source codes: http://www.github.com/...

.SH FILES
.I /home/your_user/.golem/
.RS
This folder stores temporary files, PID file etc.

.SH AUTHORS
Juda Kaleta, Daniel Švec

